builds:
- id: sos-client-bucket-lifecycle
  binary: sos-client-bucket-lifecycle
  main: ./main.go
  env:
  - CGO_ENABLED=0
  - GO_PKG=github.com/exoscale/sos-client-bucket-lifecycle
  goos:
  - linux
  goarch:
  - amd64

dockers:
- goos: linux
  goarch: amd64
  image_templates:
  - "exoscale/sos-client-bucket-lifecycle:latest"
  - "exoscale/sos-client-bucket-lifecycle:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
  dockerfile: Dockerfile.goreleaser
  build_flag_templates:
  - --pull
  - --build-arg="VERSION={{.Version}}"
  - --build-arg="VCS_REF={{.ShortCommit}}"
  - --build-arg="BUILD_DATE={{.Date}}"

release:
  github:
    owner: exoscale
    name: sos-client-bucket-lifecycle
