name: CI

on:
  push:
    branches:
    - '**'
    paths-ignore:
    - '**.md'
    - 'bucket/**'
    tags-ignore:
    - '*' # Don't run CI tests on release tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          check-latest: true
      - run: docker compose up -d --wait
      - run: go test ./... -race

