name: release

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    outputs:
      version_tag: ${{ steps.get-version-tag.outputs.version_tag }}
      linux_amd64_checksum: ${{ steps.get-linux-amd64-checksum.outputs.linux_amd64_checksum }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/build

      - name: Import GPG key
        # This is a third-party GitHub action and we trust it with our GPG key.
        # To be on the safer side, we should always pin to the commit SHA.
        # It's not a perfect mitigation, but we should always do some due diligence before upgrading.
        # The author seems trustworthy, as the author is part of the docker and goreleaser organizations on GitHub.
        uses: crazy-max/ghaction-import-gpg@72b6676b71ab476b77e676928516f6982eef7a41
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - uses: ./go.mk/.github/actions/release
        with:
          release_github_token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
          exoscale_api_key: ${{ secrets.SOS_PKG_BUCKET_KEY }}
          exoscale_api_secret: ${{ secrets.SOS_PKG_BUCKET_SECRET }}